// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Sys = require("bs-platform/lib/js/sys.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var match = Sys.argv.length > 2;

var annualSalary = match ? Caml_format.caml_int_of_string(Caml_array.caml_array_get(Sys.argv, 2)) : 0;

console.log("The annual salary is: " + String(annualSalary));

exports.annualSalary = annualSalary;
/* annualSalary Not a pure module */
