// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Sys = require("bs-platform/lib/js/sys.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var match = Sys.argv.length > 2;

var annualSalary = match ? Caml_format.caml_int_of_string(Caml_array.caml_array_get(Sys.argv, 2)) : 0;

console.log("The annual salary is: " + String(annualSalary));

function calculateTaxBracket(salary) {
  if (salary <= 18200) {
    return "Tax Bracket 1";
  } else if (salary > 18200 && salary <= 37000) {
    return "Tax Bracket 2";
  } else if (salary > 37000 && salary <= 90000) {
    return "Tax Bracket 3";
  } else if (salary > 90000 && salary <= 180000) {
    return "Tax Bracket 4";
  } else if (salary > 180000) {
    return "Tax Bracket 5";
  } else {
    return "None";
  }
}

var taxBracket = calculateTaxBracket(annualSalary);

console.log(taxBracket);

exports.annualSalary = annualSalary;
exports.calculateTaxBracket = calculateTaxBracket;
exports.taxBracket = taxBracket;
/* annualSalary Not a pure module */
